### ISSUE TITLE
‎

### ISSUE THREAD

**Issue by brourbeinsus** [Scratch-Snippets/scratch-snippets.github.io#3]
### TODO

- [x] Add at least 1 Bookmarklet

- [ ] Add at least 1 Userscript

- [ ] Add at least 1 Userstyle

### Milestones

- [ ] 5 Repository Stars
- [ ] 10 Repository Stars
- [ ] 15 Repository Stars 
- [ ] 20 Repository Stars

**Comment by imlens** [comment]
bill nye this org has died

**Comment by brourbeinsus** [comment]
> bill nye this org has died

I check from time to time, lmao
